services:
  - type: web
    name: telegram-bot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: MAIN_GROUP_ID
        sync: false
      - key: THREAD_SALES
        sync: false
      - key: THREAD_ASSORTMENT
        sync: false
      - key: THREAD_ARRIVAL
        sync: false
      - key: THREAD_PREORDER
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: telegram-bot-db
          property: connectionString
      - key: PLAN_AMOUNT
        value: 600000

databases:
  - name: telegram-bot-db
    databaseName: botdb
    user: botuser
