# Минимальная версия Python
target-version = "py311"

# Исключённые директории
exclude = [
    ".git",
    ".venv",
    "venv",
    "__pycache__",
    "alembic/versions",
    "tests/__pycache__",
]

[lint]
select = [
    "E", "W", "F", "I", "UP", "B", "C4", "SIM", "TCH"
]

ignore = [
    "E501",
    "B008",
    "SIM105",
    "RUF001",
    "RUF002",
    "RUF003",
]

fixable = ["ALL"]
unfixable = []
line-length = 100

[lint.isort]
force-single-line = false
lines-after-imports = 2
lines-between-types = 1
known-first-party = ["bot", "web_admin"]

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
